_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
batch_size:
    value: 4
learning_rate:
    value: 2e-05
max_epochs:
    value: 5
max_source_length:
    value: 1024
max_target_length:
    value: 256
model_name:
    value: facebook/bart-base
train_data_path:
    value: /Users/argy/workspace/dtu_argy/data/processed/train
val_data_path:
    value: /Users/argy/workspace/dtu_argy/data/processed/validation
