_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
